"""remove primary_key attribute of foriegn keys in cart

Revision ID: 128c8cfa2c00
Revises: f1f6c2861d25
Create Date: 2022-08-11 13:52:14.848881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128c8cfa2c00'
down_revision = 'f1f6c2861d25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    )
    op.drop_constraint('carts_pkey', 'carts', type_='primary')
    op.create_primary_key('carts_pkey', 'carts', ['id'])
    sa.PrimaryKeyConstraint('id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('carts', 'id',
                    existing_type=sa.INTEGER(),
                    server_default=None,
                    existing_nullable=False,
                    autoincrement=True)
    op.drop_constraint('carts_pkey', 'carts', type_='primary')
    op.create_primary_key('carts_pkey', 'carts', ['user_id', 'product_id'])
    # ### end Alembic commands ###
