"""update models to include order tables

Revision ID: 12b8486ceca9
Revises: a44d45f9f643
Create Date: 2022-08-09 18:02:36.635133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b8486ceca9'
down_revision = 'a44d45f9f643'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('fulfilled', sa.Boolean(), server_default=sa.text('False'), nullable=True))
    op.add_column('orders', sa.Column('coupon_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['transaction_id'])
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'coupons', ['coupon_code'], ['code'], ondelete='CASCADE')
    op.drop_column('orders', 'quantity')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('orders', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_product_id_fkey', 'orders', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('carts', 'fulfilled')
    # ### end Alembic commands ###
