"""add cart user discount product tables

Revision ID: a44d45f9f643
Revises: 
Create Date: 2022-08-07 15:41:16.083611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a44d45f9f643'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_paid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_discounts',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discounted_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('user_coupons',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_code'], ['coupons.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'coupon_code')
    )
    op.add_column('coupons', sa.Column('usage', sa.Integer(), nullable=False))
    op.add_column('coupons', sa.Column('min_amount', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('reduction', sa.Integer(), nullable=False))
    op.drop_column('coupons', 'coupon_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('coupon_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('coupons', 'reduction')
    op.drop_column('coupons', 'min_amount')
    op.drop_column('coupons', 'usage')
    op.drop_table('user_coupons')
    op.drop_table('product_discounts')
    op.drop_table('orders')
    # ### end Alembic commands ###
