"""add order_id to cart

Revision ID: f1f6c2861d25
Revises: 12b8486ceca9
Create Date: 2022-08-09 18:04:35.617801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1f6c2861d25'
down_revision = '12b8486ceca9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'carts', 'orders', ['order_id'], ['transaction_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'order_id')
    # ### end Alembic commands ###
